### ISSUE TITLE
Don't notify follow up Fire Alerts for same date/time

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/FireAlert#96]
In this case, the first fire was reported within 30 hrs. However, as there was delay in reporting, subsequent fires detected at the same time were still being triggered 2 days after the fire.

If a site has a fire recently
The expected behavior would be to check if the fire occurred after x time →eg  2 hrs, and if the alert was within 12 hrs.
Otherwise, the purpose of emergency alert wouldn't be as good.

<img width="1066" alt="Screenshot 2023-11-09 at 8 12 56 PM" src="https://github.com/Plant-for-the-Planet-org/FireAlert/assets/5401575/75fcddbd-54cc-4185-b40c-ebbf0bb7b52b">

**Comment by dhakalaashish** [comment]
These PRs fixes the issue:
#95 #103 #109 #110

**Comment by dhakalaashish** [comment]
#144 contains optimizations and improvements on the createNotification code.
